# Generated by Django 2.2.1 on 2019-10-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NibblesBookApp', '0003_auto_20191004_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.CharField(max_length=500),
        ),
    ]
