# Generated by Django 2.2.1 on 2019-10-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NibblesBookApp', '0004_auto_20191004_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='content',
            field=models.CharField(default='Good read!', max_length=600),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.CharField(max_length=50),
        ),
    ]
