# Generated by Django 2.2.1 on 2019-10-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NibblesBookApp', '0005_auto_20191004_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.CharField(default='images/author/', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.CharField(default='images/books/', max_length=50),
        ),
    ]
