# Generated by Django 2.2.1 on 2019-10-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NibblesBookApp', '0008_auto_20191005_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.CharField(default='static/images/author/', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.CharField(default='static/images/books/', max_length=50),
        ),
    ]
