# Generated by Django 2.2.1 on 2019-10-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NibblesBookApp', '0009_auto_20191006_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.CharField(default='static/images/books/', max_length=150),
        ),
    ]
