# Generated by Django 2.2.1 on 2019-10-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NibblesBookApp', '0011_auto_20191007_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
