# Generated by Django 2.2.1 on 2019-10-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NibblesBookApp', '0013_auto_20191008_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.CharField(default='static/images/books/', max_length=300),
        ),
    ]
