# Generated by Django 2.2.1 on 2019-10-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NibblesBookApp', '0014_auto_20191008_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='education',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='author',
            name='hometown',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='author',
            name='place_of_birth',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
