# Generated by Django 2.2.1 on 2019-10-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NibblesBookApp', '0015_auto_20191009_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='author',
            name='education',
        ),
        migrations.RemoveField(
            model_name='author',
            name='hometown',
        ),
        migrations.RemoveField(
            model_name='author',
            name='place_of_birth',
        ),
        migrations.AddField(
            model_name='author',
            name='about',
            field=models.CharField(default='None', max_length=700),
        ),
    ]
