# Generated by Django 2.2.1 on 2019-10-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NibblesBookApp', '0017_auto_20191009_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.CharField(default='static/images/authors/', max_length=50),
        ),
    ]
