# Generated by Django 2.2.1 on 2019-10-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NibblesBookApp', '0019_auto_20191015_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='Good read!', max_length=30),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.CharField(default='This was a good book to read!', max_length=600),
        ),
    ]
