# Generated by Django 2.2.1 on 2019-10-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NibblesBookApp', '0020_auto_20191016_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(default='This was a good book to read!', max_length=800),
        ),
    ]
