# Generated by Django 2.2.1 on 2019-10-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NibblesBookApp', '0022_auto_20191017_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(max_length=900),
        ),
    ]
